FROM node:22-slim
WORKDIR /app
COPY bridge/package.json bridge/package-lock.json ./
COPY bridge/node_modules ./node_modules/
COPY bridge/src/ ./src/
COPY bridge/tsconfig.json .
CMD ["npx", "ts-node", "src/server.ts"]
